# Generated by Django 2.1.7 on 2020-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=True),
        ),
    ]
